import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pepperoni Gluten-Free Pizza',
    cookTime: '10-20',
    price: 12,
    favorite: false,
    origins: ['italy'],
    stars: 4.8,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Grilled Meatballs',
    price: 22,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch', 'GlutenFree'],
  },
  {
    id:'3',
    name: 'Gluten-Free Hamburger',
    price: 7,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 4.0,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Burger'],
  },
  {
    id:'4',
    name: 'Gluten-Free Fried Potatoes',
    price: 3,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 4.2,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup (Gluten-Free)',
    price: 13,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 4.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup', 'GlutenFree'],
  },
  {
    id:'6',
    name: 'Gluten-Free Vegetable Pizza',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.3,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Gluten-Free Burger',
    price: 14,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    stars: 4.4,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Gluten-Free Vegetables Magento Pizza',
    price: 9,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 8 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 3 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Burger', count: 2 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
  { name: 'GlutenFree', count: 8 },
]
